ecoacoustics/web-components

.github/workflows/preview.yml

It generated a lot of noisy notifications and the messages were particularly useless on commits that get squashed.

chore(ci): disable commit messages for docs deploy

---

src/components/media-controls/media-controls.ts
src/components/verification-grid-settings/css/style.css
src/components/verification-grid-settings/verification-grid-settings.fixture.ts
src/components/verification-grid-settings/verification-grid-settings.spec.ts
src/components/verification-grid-settings/verification-grid-settings.ts
src/components/verification-grid/verification-grid.ts
src/helpers/advancedTypes.ts
src/tests/helpers.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

This pull request exposes a user interface to change the verification grid size after creation
- Adds a button to change the verification grid size
- Fix a bug where increasing the grid size after initalization would not cause the new spectrograms to generate
- Fix a bug where if the same URL was used for two grid tiles in the same position, the subject model would not update
- Corrects typing of media controls `changeNumberHandlerEvent` callback to a `HTMLInputElement` `Event` instead of a `SLMenuItem` event
Because this PR exposes the verification grid size to the user #146, and #147 become much more prevelant because the user can input grid sizes that (obviously) won't fit on their screen and start scrolling.
_A new scrollbar + label that can be used to change the verification grid …

Add UI to change verification grid size

---

.eslintignore
.github/workflows/tests.yml
.prettierignore
playwright.config.ts
src/components/data-source/data-source.spec.ts
src/components/decision/decision.fixture.ts
src/components/indicator/indicator.fixture.ts
src/components/indicator/indicator.ts
src/components/info-card/info-card.spec.ts
src/components/spectrogram/spectrogram.spec.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-settings/verification-grid-settings.fixture.ts
src/components/verification-grid-tile/verification-grid-tile.fixture.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/helpers/userAgent.ts
src/tests/indicator-spectrogram/indicator-spectrogram-media-controls.e2e.fixture.ts
src/tests/indicator-spectrogram/indicator-spectrogram-media-controls.e2e.spec.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

This pull request changes the keyboard shortcuts on MacOS to reflect their native bindings.
- Adds tests for sub-selection
- CI tests used to only cover Chrome on Ubuntu. The test matrix now tests Chrome, Firefox, and Safari on all major platforms (Ubuntu, Windows, MacOS)
- CI now uploads a test report once all tests are complete
- Fixes a bug where shift-clicking range selection did not work when using tablet mode
- Fixes a bug where a verification grid with tablet mode selection would not hide the skip buttons shortcut key
- `Ctrl + A` to select all is now `Cmd + A` on MacOS
- `Ctrl + D` to select all is now `Cmd + D` on MacOS
- `Alt + Number` now works for selecting tiles on MacOS
- Pressing escape now de-selects all tiles on MacOS
- `node_modules/` and `pnpm-lock.yaml` are now …

Shortcuts should reflect native bindings

---

dev/verification-grid.html
package.json
pnpm-lock.yaml
src/components/index.ts
src/components/media-controls/css/style.css
src/components/media-controls/media-controls.ts
src/components/spectrogram/spectrogram.spec.ts
src/components/verification-grid-settings/verification-grid-settings.ts
src/services/shoelaceLoader.ts
vite.config.ts

Previously, shoelace icons were not bundled during a production build, meaning that the media controls and other similar locations would have an empty placeholder where the icon should be.
This PR adds the shoelace icons to the production build by assigning each icon's SVG to a variable in the bundle's barrel file.
I have chosen this solution because
- We have to support offline usage (meaning that we can't use a CDN), and all assets must be included in the build
- I inlined the SVGs into the barrel file because shipping an additional dependency (in the form of a seperate SVG file in the `assets/` directory) increases the complexity of deploying the web components because it requires you to: correctly set up CORS for this external file, serve the external file with the correct MIME type, …

Fix: Icons not being included in production build

---

docs-src/examples/index.md
docs-src/examples/verification/classification.md
public/test-items.json
src/components/decision/decision.spec.ts
src/components/decision/decision.ts
src/components/info-card/info-card.ts
src/components/verification-grid-tile/css/style.css
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/helpers/themes/theming.css
src/tests/helpers.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

- Adds a segmented meter to each grid tile which displays what tasks have or have not been completed for the given tile
- Fixes some leaky tests in `decision.spec.ts` which could cause other tests to incorrectly fail
- Do not show a decision highlight for a skip decision
- Fix a bug where [Object object] would be shown in the tile figure title if there was no `tag` column in the dataset
- Remove empty `.gitkeep` file from e2e test folder (`/e2e/`)
- Adds `tag` column to the verification grid test dataset
- Re-order some info-cards properties to reflect the code-style.md (context's should come first)
- `RequiredClassificationTags` no longer returns duplicate tag models
This was originally here because we did not have any e2e tests, but still wanted the directory to exist so that Playwright …

Show completed actions in segmented meter

---

src/components/axes/css/style.css
src/components/data-source/data-source.ts
src/components/decision/classification/classification.ts
src/components/decision/css/style.css
src/components/decision/decision.ts
src/components/index.ts
src/components/indicator/css/style.css
src/components/progress-bar/css/style.css
src/components/progress-bar/progress-bar.ts
src/components/progress-bar/progrss-bar.fixture.ts
src/components/progress-bar/progrss-bar.spec.ts
src/components/spectrogram/css/style.css
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-tile/css/style.css
src/components/verification-grid/css/style.css
src/components/verification-grid/verification-grid.ts
src/helpers/audio/worker.ts
src/helpers/themes/theming.css
src/services/gridPageFetcher.ts
src/tests/axes-spectrogram/axes-spectrogram.e2e.spec.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts
webcomponents.code-workspace

A short description of the pull request
- Add progress bar to verification grid to show how far through the dataset the user is
- Adds `aria-label` to classification component buttons (tested with screenreaders)
- Moves the `1rem` `kbd` element height to the abstract decision component. This was done so that the fixed `kbd` element height is does not apply to the `kbd` element helpers shown during `Alt` + `#` selection or in the help dialog
- During Playwright tests, the spectrogram container used to grow indefinitely. This has now been correctly fixed meaning that tests are **much** less flakey, and easier to develop. It also fixes tests failing on the main branch
None
_A progress bar when **not** viewing history_
---
_A progress bar **when** viewing history_
In this image, I am viewing …

Add a progress bar to show dataset progress

---

dev/spectrogram.html
src/components/axes/axes.fixture.ts
src/components/data-source/data-source.fixture.ts
src/components/decision/classification/classification.fixture.ts
src/components/decision/verification/verification.fixture.ts
src/components/indicator/indicator.fixture.ts
src/components/info-card/info-card.fixture.ts
src/components/media-controls/media-controls.fixture.ts
src/components/progress-bar/progrss-bar.fixture.ts
src/components/spectrogram/single-spectrogram.fixture.ts
src/components/spectrogram/spectrogram.spec.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-settings/verification-grid-settings.fixture.ts
src/components/verification-grid-tile/verification-grid-tile.fixture.ts
src/components/verification-grid/verification-grid.fixture.ts
src/services/modelParser.spec.ts
src/services/verificationParser.spec.ts
src/tests/assertions.ts
src/tests/axes-spectrogram/axes-spectrogram.e2e.fixture.ts
src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
src/tests/indicator-spectrogram/indicator-spectrogram-media-controls.e2e.fixture.ts
src/tests/spectrogram-media-controls/spectrogram-media-controls.e2e.fixture.ts
src/tests/spectrogram-media-controls/spectrogram-media-controls.e2e.spec.ts
src/tests/test-bed.spec.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
webcomponents.code-workspace

This fixes a bug where the error "Connect can only be called once." would
be thrown due to the spectrogram rendering twice in the firstUpdated()
and again in updated() lifecycle methods.
This commit also adds additional conditions to the base Playwright
fixture to fail if any browser errors are thrown.
- Fixes a bug where the spectrograms `renderSpectrogram()` method was called in both `firstUpdated` and `updated`
- Fixes a bug where adding audio source to a spectrogram component through the default slot would not cause it to check if it had to regenerate, or do an initial render
- Fixes a bug where the spectrogram could fail to change its source if spectrogram options were also updated in the same update cycle
- Playwright tests now fail if an error is thrown in the browser
Fixes: #200

Fix: Spectrograms performing double initial render

---

src/components/data-source/data-source.ts
src/components/verification-grid/verification-grid.ts
src/helpers/attributes.ts
src/services/gridPageFetcher.ts

- Adds the ability to provide a `urlTransformer` to the verification grid that will be run over every subject URL. This is useful for URL parameter based authentication, and improved caching through file hashes
Fixes: #208

Feat: Add the ability to transform subject urls

---

.github/workflows/docs-publish.yml

Because our documentation website is published through the release workflow, we could previously not publish a version of the documentation website without also publishing a web components release.
This commit allows us to manually run the documentation publish workflow, allowing us to publish the documentation website without publishing a new version of the web components to npm.
Because we did not release a web components version with the goshawk verification deployment, the goshawk verification interface was never deployed to production.
- Allows manually triggering the website publishing workflow. Allowing us to publish the website while not publishing a new web components version

CI: Allow manual trigger to run website publishing

---

dev/verification-grid.html
src/components/decision/classification/classification.fixture.ts
src/components/decision/decision.ts
src/components/decision/verification/verification.fixture.ts
src/components/media-controls/media-controls.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts
webcomponents.code-workspace

Fixes keyboard shortcuts being bound at the document level.
This resolves bugs where if the web components were embedded into a host application with an input box, typing in the input box could trigger decision events via shortcut keys.
- Reassign document-level event listeners for actioned shortcut keys to verification grid
- Decision button shortcuts now listen for keyboard events on the verification grid component
- Media controls "space to play" now listens for keyboard events on the verification grid component
- Space to play now checks if the event originated from within an `input` element. Meaning that if the user places an `input` component inside the grid tile slot, it will not trigger a play event when typing inside the input box
- Preventing "space to scroll" is now the …

Fix: Reduce focus area for keyboard shortcuts

---

dev/cdn.html
index.html
package.json
src/components/decision/decision.ts
src/components/index.ts
src/components/info-card/info-card.ts
src/components/logger/logger.ts
src/components/media-controls/media-controls.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-settings/verification-grid-settings.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/helpers/constants/contextTokens.ts
src/helpers/resizeObserver.ts
src/polyfills/userAgentData.ts
vite.config.ts

Adds the ability for users to import tree-shaken ESM modules in their third-party applications.
Usage: `import "@ecoacoustics/web-components/components/spectrogram`
- Each web component now has its own JavaScript build target under `components/[name].js`
- Moves context tokens and other constants to a `constants.ts` file
- Changes published directory to `dist/`
- Fix a potential race condition in resize observers where they would attempt to disconnect even if the component never rendered (first lifecycle was not complete)
- Fix a bug where polyfills were not idempotent causing errors if the components were imported twice into the same page
Fixes: #219

feat(build): Emit ESM modules in build output

---

.github/workflows/docs-publish.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/tests.yml

GitHub limits free lfs asset transfers to 1GB a month
However, because our workflows download a lot of assets, we quickly exceeded this limit
This PR replaces the default `actions/checkout@4` for the `nschloe/action-cached-lfs-checkout@v1` action that uses `actions/cache` under the hood to cache lfs assets.
This should help reduce our lfs asset transfers
- Use `nschloe/action-cached-lfs-checkout@v1` for cached lfs asset checkout
Fixes: #215

ci(dependencies): Cache lfs assets in checkout

---

dev/verification-grid.html
docs-src/_includes/layouts/deployment.11ty.js
docs-src/_includes/page.11ty.js
eleventy.config.js
package.json
src/components/verification-grid/verification-grid.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

- Fixes a bug where increasing the grid size would not cause new grid tiles to be highlightable
- Fixes a bug where non-zero offset verification grids would have misaligned highlight box intersection checks
- Fixes a bug where the highlight box would not disappear when changing mobile browser site settings from "desktop mode" to the default mobile mode when highlighting
- Fixes a bug where the selection highlight box would not recognise new grid tiles if they were added/removed while highlighting (typically occurred in dynamic grid size shrinking)
- Fix netlify site still using old build asset locations
- Use pointer events for highlight selection box
- Update pnpm corepack version
Fixes: #187

fix(grid): Highlight selection after resizing grid

---

docs-src/deployments/cane-toads.md
src/components/data-source/data-source.ts
src/services/gridPageFetcher.ts
src/services/modelParser.ts
src/services/subjectParser.ts

- Adds a cane-toads deployment to the docs website
- Adds quick and dirty hack to support parsing "Common.Name" fields
- Fixes a bug where the tag object would be emitted in verification result downloads (uplifed fix from #240)
_A popup prompting the validator to provide their authentication token (so they can access the private ecosounds project (FireFox)_
_A popup prompting the validator to provide their authentication token (so they can access the private ecosounds project (Chrome)_
_The cane-toads verification interface deployment (with redacted spectrograms & axes for data-privacy)_
This PR opens up a new issue to propperly support "upper-case dot-cased" fields (e.g. "Common.Name")

docs: Add cane toads verification deployment

---

dev/use-cases/ecosounds.html
src/models/subject.spec.ts
src/models/subject.ts

- The `SubjectWrapper`'s `toDownloadable` method now calls `toJSON` on the original subject when attempting to download results
- Updates the ecosounds page with an subject injector that should not be emitted by the `toJSON` result

fix: support calling toJSON on downloaded subjects

---

docs-src/deployments/verification.md

This pull request duplicates the cane-toads verification deployment to a more generic `/deployments/verification` URL.
Usually I'd avoid duplicating a deployment. However, I have decided to duplicate the deployment because:
- In the interest of time, duplicating a known working deployment is least likely to produce bugs and unforeseen regressions
- We could use a 11ty template, but this duplication will only happen once
- We have to maintain the `cane-toads` deployment because an external user is using this endpoint on a regular basis
- Maintaining a symlinked directory might be possible, but it has the potential to produce bugs
- It does not increase the web component bundle size and does not increase the docs website size (because we are using ssg)

docs: Add generic verification deployment

---

dev/use-cases/nsw.html
src/components/data-source/data-source.ts
src/services/urlSourcedFetcher.ts

- Fixes a bug where the file name of locally supplied results would be a blob URL
- Changes the `data-source` property to a `string | File` polymorphic type, so that the file name can be different from the `src` url
Fixes: #261

fix: Incorrect file name for local results

---

src/components/media-controls/media-controls.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/helpers/keyboard.ts
src/tests/full-spectrogram/full-spectrogram.e2e.fixture.ts
src/tests/full-spectrogram/full-spectrogram.e2e.spec.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

- Pressing space with no selection now makes all tiles in the verification grid play
- The grid tile play event aborter is now in the verification grid (needed to check the grid size)
- Fixes not being able to play a 1x1 verification grid tile with space
Fixes: #128
Fixes: #258

fix: Space to play with no grid selection should play all

---

dev/use-cases/ecosounds.html
docs-src/components.11ty.js
src/components/decision/classification/classification.ts
src/components/decision/decision.ts
src/components/decision/verification/verification.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/tests/helpers.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

At the moment the verification grid `decision-made` event emits a tuple of `[VerificationGridTile, DecisionModel]`. This is poor form for multiple reasons such as:
- The verification grid tile is an internal component, and should not be exposed to the user
- Emitting a tuple is not ergonomic
- Using the verification grid tile reference to get the subject model is error-prone. Because if the verification grid auto-pages before the subject model could be evaluated, it could change
- The verification-grids `decision-made` event now emits a `SubjectWrapper` model which contains the `tag`, `subject`, `verification`, and `classification` models
Fixes: #294

Emit SubjectWrapper in verification grid decision-made event

---

docs-src/deployments/a2o-classification.md

I have purposely left the deployment name generic because the stakeholder says that they might want to add/remove/edit tags in the future.
Leaving the deployment name generic means that the link can remain the even if the purpose of the deployment changes.
Add A2O classification deployment

docs: Add A2O classification deployment

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/publish.yml
README.md
dev/cdn.html
docs-src/examples/create-verification-grid.md
docs-src/index.md
docs-src/spectrogram-creator/index.md

This repository used to be named webcomponents-workspace, but we have since changed the name to web-components. However, some documentation still used the old (incorrect) package name.
Additionally, the documentation was inconsistent about what CDN path people should use.
This PR updates old references to the old `webcomponent-workspace` repo, and unifies the messaging on what CDN path to use.
Fixes: #310

fix(docs): Outdated and inconsistent examples

---

README.md
dev/cdn.html
docs-src/examples/create-verification-grid.md
docs-src/index.md

This pull request removes all references to esm.run from the documentation.
`esm.run` breaks audio worklet dynamic imports
Fixes: #313

docs: Deprecate esm.run from cdn documentation

---

src/components/media-controls/media-controls.ts
src/components/spectrogram/single-spectrogram.fixture.ts
src/components/spectrogram/spectrogram.spec.ts
src/components/spectrogram/spectrogram.ts
webcomponents.code-workspace

This commit adds rubber banding for interpolated time values and
now requires an audio element to emit a time update before time
interpolation begins.
- If audio fails to be fetched, the spectrogram components playback will no longer break for all future audio (this caused a lot of problems in the verification grid where if one audio file failed to load, all subsequent audio playback from that spectrogram component would break.
- Fix a bug where the indicator line could go past the end of the audio
- Fix a bug where the `currentTime` (e.g. indicator line) could become desynced with the real audio time, causing the indicator line to be in the wrong position. This was easy to see if you held down the space bar on a spectrogram (try it on the old and new spectrogram creator).
- Fix a bug …

fix: De-sync of audio and spectrogram currentTime

---

src/services/urlSourcedFetcher.ts

Firefox ESR on Windows was reporting .csv file types as excel files. To fix this, we now check if an "excel" file type also has a .csv extension. It does, we parse the file as a csv file.
- If an "excel" file type is uploaded with the ".csv" extension, we attempt to parse the file as a csv. This was done because Firefox ESR on Windows reports csv files as an "application/vnd.ms-excel" file type.
We currently have tests to cover this, but CI only tests against greenfield versions of the browsers, meaning that this bug was not caught during testing / ci.
Adding ESR versions of Firefox and Chrome to CI would have caught this bug, but adding these browsers would double CI expenses for not much additional benefit.
Fixes: #243

fix: Local .csv data sources not being recognised

---

dev/use-cases/shoelace-host.html
src/components/spectrogram/spectrogram.spec.ts
src/components/spectrogram/spectrogram.ts
src/components/verification-grid/verification-grid.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts
webcomponents.code-workspace

The verification grid now takes an optional attribute `progress-bar`
that can change the position of the progress bar to either "bottom"
(default), "top", or "hidden".
- Adds `progress-bar-position` attribute to verification grid
- Is `progress` the best name for this attribute? `progress` sounds like an override for where the decision head. If we are ok using a more verbose attribute name, we could use something like `progress-position`
- You cannot target the progress bar with css parts. Is this something we want to support? If so, I'll have to do some testing/refactoring to ensure that the progress bar is compatible with user configurable css (e.g. If we want `part` support, I need to ensure changing the `display` type, sizing, margin, padding, works correctly)
Fixes: #369 …

feat: Grid attribute to change progress position

---

src/components/verification-grid-tile/css/style.css
src/components/verification-grid-tile/verification-grid-tile.fixture.ts
src/components/verification-grid-tile/verification-grid-tile.spec.ts
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts

- Adds `isOnlyTile` property to `oe-verification-grid-tile` component
- Use the `auto` cursor on when on a 1x1 grid
- Removes a lot of skipped tests that are currently tested in the `verification-grid.e2e.spec` tests
Fixes: #386

fix: Don't show "pointer" cursor on 1x1 grids

---

src/components/media-controls/media-controls.fixture.ts
src/components/media-controls/media-controls.spec.ts
src/components/media-controls/media-controls.ts

- Allows the media-controls `for` property to take a `SpectrogramComponent` element reference
Using an element ref should make the Workbench's search page much faster.
Fixes: #360
This branch was created to test the new [Gemini CLI](https://cloud.google.com/gemini/docs/codeassist/gemini-cli), and see how far I could get by "TDD vibe coding". I just coined the term "TDD vibe coding". I don't know if it's a "formalized" version of "vibe coding", if my term is correct, or if anyone else has written a blog on coding like this.
Turns out, I could complete this issue in 10 minutes.
I originally tried telling Gemini to complete the task with some instructions on what I wanted it to do. It didn't complete the task and went off and started modifying unrelated code.
However, I achieved a much …

feat: element ref ability inmedia-controls "for"

---

package.json
pnpm-lock.yaml
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts

- Changes grid tile's `loaded` event name to `tile-loaded`
- Removes duplicate state for button disabled state
Fixes: #420

fix: Overloaded "loaded" event

---

package.json
src/components/verification-grid/verification-grid.ts
src/models/subject.ts
vite.config.ts

Immediately deprecated upon landing, this property is an escape hatch so when unsetting `newTag`s (or any other property) host applications can use the old value to issue DELETE requests.
This is a hacky solution to a more permanent solution I'd like to discuss in https://github.com/ecoacoustics/web-components/issues/448
- `decision-made` values now emit an `oldSubject` property that contains a shallow copy of the `SubjectWrapper` object before any decision modifications were made
- When a decision is **changes** to `unique symbol("no-decision-required")` from an instantiated decision, it now emits a `decision-made` event
- Exports the `noDecisionRequired` symbol as a valid package entrypoint so that consumers can use this symbol in comparisons to see if a decision was updated due to …

feat: Emit oldSubject in decision-made event

---

dev/use-cases/ecosounds.html
src/components/decision/skip/skip.ts
src/components/verification-grid/verification-grid.ts
src/index.ts
src/tests/verification-grid/verification-grid.e2e.fixture.ts
vite.config.ts

This is not a breaking change because you can still use `oe-verification[skip="false"]` but this adds an `oe-skip` component which will stand alone in interfaces and not try to join onto the `oe-verification` button group.
Note that this doesn't fix the squaring issue, but is a quick fix for the sqauring bug on Ecosounds while chipping away at work which we want to do.
- Adds standalone `oe-skip` button which does not try to join to other `oe-verification` components
Fixes: #446
_New `oe-skip` decision button on Ecosounds showing that it fixes visual bugs with new button order_

feat: Add oe-skip button

---

src/components/progress-bar/css/style.css

When we changed the `--oe-panel-color` to the `--oe-background-color` I didn't correctly adjust the `oe-progress-bar`'s undecided color.
This meant that the "undecided" portion of the progress bar blended perfectly with the background color, making it "invisible".
- Use `--oe-panel-color-dark` for progress bars undecided color
_Example of the progress bar with "undecided" color. This progress bar shows the "view head", "completed" and "no decision" colors. The no decision color is the small far right hand side color._
If you want me to increase the contrast again, we do have an `--oe-panel-color-darker` which is used in the bootstrap dialog.
Fixes: #469

fix: contrast for progress bar's undecided color

---

dev/use-cases/nsw.html
src/components/verification-grid-tile/verification-grid-tile.ts
src/components/verification-grid/verification-grid.ts
src/tests/verification-grid/verification-grid.e2e.spec.ts

If you used to sub-select multiple tiles, then press "skip" the decision meter would not update correctly. This PR fixes this bug
- Fixes bug where pressing "skip" with sub selection wouldn't cause the selected tiles progress meter to update
Fixes: #494

fix: Skip decisions not showing in progress meter

---

dev/use-cases/shoelace-host-dark.html
src/components/verification-grid/css/style.css
src/components/verification-grid/verification-grid.ts

- Removes box shadow for single tile views
_Single tile view without box shadow_
---
_unchanged MxN grid with red box shadow for easy viewing_
Fixes: #517

fix: Removes box shadow for single tile views

---

src/components/verification-grid/verification-grid.ts

- Fixes top positioned progress bar being too small
_Top positioned progress bar + pagination controls_
Fixes: #508

fix: Width of top positioned progress bar

---

src/components/indicator/indicator.spec.ts
src/components/indicator/indicator.ts

This fixes visual jank and layout shift of indicators before spectrograms are rendered.
Check out the "spectrogram creator" on the doc website. You should see less jank on first render.
[Screencast from 2025-09-18 15-54-42.webm](https://github.com/user-attachments/assets/254b9838-ea6c-43c9-a102-48e628b91fc5)
_Before changes (with CPU throttling for better viewing)_
---
[Screencast from 2025-09-18 15-56-04.webm](https://github.com/user-attachments/assets/866f7dcb-460b-40a3-9694-dcd23ef3a5f2)
_After changes_
There is still a bit of jank due to #414 (Axes component should reserve space for labels before audio model initialization) which causes the indicator and axes labels to overlap for a single render cycle. (remember that videos above are 20x slower than a typical user, so this jank is …

fix: Don't render indicator without unit converter

---

README.md
dev/annotation-edge-cases.html
dev/cherry-picked.html
docs-src/examples/search.md
src/components/spectrogram/single-spectrogram.fixture.ts
src/components/spectrogram/spectrogram.ts
src/helpers/audio/colors.ts

fix: Use "audacity" as default color map
